
ALTER TABLE "RoundResult"
ADD COLUMN IF NOT EXISTS "diasSemVenda" INTEGER,
ADD COLUMN IF NOT EXISTS "eventosAplicados" JSONB,
ADD COLUMN IF NOT EXISTS "valorPenalidade" DOUBLE PRECISION;

ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SEGURANCA';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'BALANCA_FREEZER';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'REDES';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SITE';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SELF_CHECKOUT';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'MELHORIA_CONTINUA';
